### ISSUE TITLE
Clarify "normal user"

### ISSUE THREAD

**Issue by csarven** [solid/userguide#17]
re https://github.com/solid/userguide/#role "normal user", it is unclear if that is about a set of core capabilities or options available to all users with different (some?) roles.

Is it actually a role?

How can the "normal user" role be selected or deselected?

Does it require the actor to be authenticated?

**Comment by michielbdejong** [comment]
I think 'normal' is what's left when you untick both 'developer' and 'power user'.

**Comment by brownhoward** [comment]
'Normal' is as @michielbdejong described above. Maybe a better term would be "Default"?

**Comment by csarven** [comment]
I think some cues can help.

There is no indication as to what the container with the role names entail. Does it actually call out for action?

Can more than one be selected? How? (This is not obvious for everyone to do)

`select` is a bit awkward to work with for something like this.

Consider the following to help clarify:

* Include short description about what the user can do. May want to indicate which role the user is currently in (eg. "normal" or "default" and that's totally cool), and that they can select multiple roles if they want to.
* Use `fieldset` to group the roles with `legend` "Roles".
* Use `input=checkbox` + `label=for` (instead of `option`) per role. Easy to select a role at a time, and for multiple role selections, it doesn't require key or click combinations.
* Reuse text from userguide#roles for the short description of a role either after each `label` or have a `title` (for tooltip) or some other indicator to help find out about the capabilities.

**Comment by brownhoward** [comment]
I'll update the Userguide (https://github.com/solid/userguide#role and https://github.com/solid/userguide/blob/master/appendix/userroles.md) text to clarify the role of the "Normal User" and how to select multiples Roles (there is a tip in https://github.com/solid/userguide#role but the workflow could be highlighted).

The remainder of the comments really refer to enhancements of the Data Browser preferences UX so I'll create a linked ticket in the solid-panes repo: https://github.com/solid/solid-panes/issues/223
