### ISSUE TITLE
Notepad link gives a 404

### ISSUE THREAD

**Issue by SharonStrats** [solid/userguide#20]
There are two places that refer to NotePad when you click on this link it takes you to https://github.com/solid/userguide/blob/master/views/views/notepad/userguide.md which gives a 404 error.

**Comment by michielbdejong** [comment]
@SharonStrats the fixed link is (but don't get too excited because there's not much there...) [this one](https://github.com/solid/userguide/blob/master/views/notepad/userguide.md)

**Comment by michielbdejong** [comment]
Hmmm, if only we could find a volunteer to fill out more details in that user guide page for the Notepad... ;)

Someone who knows a lot about the Notepad, maybe, hmmm.. ;)

**Comment by SharonStrats** [comment]
Okay, no problem!  I will fix it :)
