### ISSUE TITLE
FutureLearn's MEGA ISSUES with solid/userguide THREAD

### ISSUE THREAD

**Issue by FutureLearnSole** [solid/userguide#23]
### LIVING DOCUMENT
<p align="right"><i>💜clicking on the expand-icon is great and all, but FutureLearn dragOpens() his SoLiD resources, and you ought to as well.. </i></p>
<a href="https://ipfs.io/ipfs/QmeqSVyY5A69vkZssn3dRLkJtvpZUL5ovEPFmPstYTybvd?filename=dragOpenC39hZERbxF.gif"><img src="https://ipfs.io/ipfs/QmeqSVyY5A69vkZssn3dRLkJtvpZUL5ovEPFmPstYTybvd?filename=dragOpenC39hZERbxF.gif" align="centre"></a>

**Comment by brownhoward** [comment]
@FutureLearnSole Thanks for the comment. I use the ability to view a resource by clicking-and-dragging the name up to the tab bar a lot myself. Just created a PR to add a tip explaining this in the readme.

**Comment by brownhoward** [comment]
Resolved by PR #24.
