### ISSUE TITLE
Clarify how to get a draggable URI bar icon

### ISSUE THREAD

**Issue by timbl** [solid/userguide#27]
You can't use sing the same tab for the friends list they were browsing and for the uri of the person you are trying to add. You need to use a different tab.
When  you are adding a new URI to the bar, but not pressing enter, then you are leaving the browser confused. You are thikng about going to yiour friend but you have not gone. so it stops the icon being dragable until you have decided whether you are looking at your friends list or your friend.  Need to clarify.

**Comment by Ryuno-Ki** [comment]
I'm confused. I hope that this is clear to everybody involved (sounds like a note taken after a meeting to me).
Perhaps a (annotated?) screenshot or a video would help outline the problem.

„draggable URI bar icon” is the favicon? Or a part of the UI? Where does it get dragged to which place? etc. pp.

**Comment by brownhoward** [comment]
I understood this as asking for clarification on https://github.com/solid/userguide/blob/main/views/friends/userguide.md#add-a-new-friend. Specifically that to perform the drag-and-drop to add a new Friend, you need to be using 2 tabs/browsers to display:

1. Friends view.
2. Profile of the user you want to add as a friend.

And if you just enter the WebID in the browser address bar but do not press 'Enter', then the address bar icon (to the left of the WebID) does not reference the entered WebID and cannot be used for drag-and-drop).

A similar update probably needs to be done for the Tip under https://github.com/solid/userguide/blob/main/views/sharing/userguide.md#add.

**Comment by Ryuno-Ki** [comment]
Thanks kevin!
That should make it easier to make sense of this issue in case it becomes stale.

**Comment by brownhoward** [comment]
Submitted PR #28 for review.

**Comment by brownhoward** [comment]
Related PR merged.
