### ISSUE TITLE
Update to solidos auth-upgrade

### ISSUE THREAD

**Issue by bourgeoa** [solid/userguide#30]

**Comment by timea-solid** [comment]
I cannot think of anything on the frontend that needs to be reported about the auth upgrade directly in the userguide. 
So I added the documentation under solidOS here: https://github.com/solid/solidos/blob/main/documentation/auth-upgrade-to-use-DPoP.md
Needs improvements of course.

**Comment by bourgeoa** [comment]
Screen copy is ok.
We need to consider that the login screen is server related.

**Comment by timea-solid** [comment]
Ok, for that purpose I link the discussion of how the registration/login has changed as a reference here: https://github.com/solid/solidos/discussions/54
I think this is however UX related and not user guide material. 
@bourgeoa Is this enough?

**Comment by bourgeoa** [comment]
I was more thinking of adding a comment saying that the screenshot is from NSS and is server dependant.
But may be it not needed

**Comment by timea-solid** [comment]
@bourgeoa  Do you mean this: https://github.com/solid/userguide/issues/30#issuecomment-1047696638 or another diagram?

**Comment by angelo-v** [comment]
Perhaps we need to add an info for the log out, because when you log out from SolidOS that does not mean you log out from your Pod provider, so when you log in again you won't be asked for your password again.

**Comment by timea-solid** [comment]
Thank you for the feedback. I have updated the documentation: https://github.com/SolidOS/solidos/blob/main/documentation/auth-upgrade-to-use-DPoP.md
